import { SensorReading } from '@/hooks/useSensorData';

export const exportToJSON = (data: SensorReading[], filename: string = 'sensor-data') => {
  const exportData = {
    exportDate: new Date().toISOString(),
    totalReadings: data.length,
    readings: data.map((reading) => ({
      ...reading,
      timestamp: reading.timestamp.toISOString(),
    })),
    summary: calculateSummary(data),
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], {
    type: 'application/json',
  });
  
  downloadFile(blob, `${filename}-${Date.now()}.json`);
};

export const exportToCSV = (data: SensorReading[], filename: string = 'sensor-data') => {
  const headers = [
    'Timestamp',
    'Moisture (%)',
    'Humidity (%)',
    'Temperature (°C)',
    'Nitrogen (mg/kg)',
    'Phosphorus (mg/kg)',
    'Potassium (mg/kg)',
    'pH',
    'EC (mS/cm)',
  ];

  const rows = data.map((reading) => [
    reading.timestamp.toISOString(),
    reading.moisture,
    reading.humidity,
    reading.temperature,
    reading.nitrogen,
    reading.phosphorus,
    reading.potassium,
    reading.ph,
    reading.ec,
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map((row) => row.join(',')),
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv' });
  downloadFile(blob, `${filename}-${Date.now()}.csv`);
};

export const exportWeeklySummary = (data: SensorReading[]) => {
  const summary = calculateSummary(data);
  
  const reportContent = `
WEEKLY SOIL MONITORING SUMMARY
==============================
Generated: ${new Date().toLocaleDateString()}
Period: Last 7 Days
Total Readings: ${data.length}

SENSOR AVERAGES
---------------
Moisture: ${summary.moisture.avg}% (Range: ${summary.moisture.min}-${summary.moisture.max}%)
Humidity: ${summary.humidity.avg}% (Range: ${summary.humidity.min}-${summary.humidity.max}%)
Temperature: ${summary.temperature.avg}°C (Range: ${summary.temperature.min}-${summary.temperature.max}°C)
Nitrogen: ${summary.nitrogen.avg} mg/kg
Phosphorus: ${summary.phosphorus.avg} mg/kg
Potassium: ${summary.potassium.avg} mg/kg
pH Level: ${summary.ph.avg}
EC: ${summary.ec.avg} mS/cm

HEALTH ASSESSMENT
-----------------
Overall Status: ${getHealthStatus(summary)}

RECOMMENDATIONS
---------------
${getRecommendations(summary).join('\n')}

---
Report generated by Smart Soil Monitoring System
  `.trim();

  const blob = new Blob([reportContent], { type: 'text/plain' });
  downloadFile(blob, `weekly-summary-${Date.now()}.txt`);
};

const downloadFile = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

interface SensorStats {
  avg: number;
  min: number;
  max: number;
}

interface Summary {
  moisture: SensorStats;
  humidity: SensorStats;
  temperature: SensorStats;
  nitrogen: SensorStats;
  phosphorus: SensorStats;
  potassium: SensorStats;
  ph: SensorStats;
  ec: SensorStats;
}

const calculateSummary = (data: SensorReading[]): Summary => {
  const calcStats = (values: number[]): SensorStats => ({
    avg: Number((values.reduce((a, b) => a + b, 0) / values.length).toFixed(1)),
    min: Number(Math.min(...values).toFixed(1)),
    max: Number(Math.max(...values).toFixed(1)),
  });

  return {
    moisture: calcStats(data.map((d) => d.moisture)),
    humidity: calcStats(data.map((d) => d.humidity)),
    temperature: calcStats(data.map((d) => d.temperature)),
    nitrogen: calcStats(data.map((d) => d.nitrogen)),
    phosphorus: calcStats(data.map((d) => d.phosphorus)),
    potassium: calcStats(data.map((d) => d.potassium)),
    ph: calcStats(data.map((d) => d.ph)),
    ec: calcStats(data.map((d) => d.ec)),
  };
};

const getHealthStatus = (summary: Summary): string => {
  let score = 0;
  
  if (summary.moisture.avg >= 40 && summary.moisture.avg <= 60) score++;
  if (summary.ph.avg >= 6.0 && summary.ph.avg <= 7.5) score++;
  if (summary.nitrogen.avg >= 30 && summary.nitrogen.avg <= 70) score++;
  if (summary.temperature.avg >= 18 && summary.temperature.avg <= 28) score++;
  
  if (score >= 3) return 'HEALTHY - Optimal conditions for most crops';
  if (score >= 2) return 'MODERATE - Some parameters need attention';
  return 'NEEDS ATTENTION - Multiple parameters outside optimal range';
};

const getRecommendations = (summary: Summary): string[] => {
  const recommendations: string[] = [];
  
  if (summary.moisture.avg < 40) {
    recommendations.push('• Increase irrigation frequency');
  } else if (summary.moisture.avg > 65) {
    recommendations.push('• Reduce watering to prevent waterlogging');
  }
  
  if (summary.ph.avg < 6.0) {
    recommendations.push('• Apply lime to raise soil pH');
  } else if (summary.ph.avg > 7.5) {
    recommendations.push('• Apply sulfur to lower soil pH');
  }
  
  if (summary.nitrogen.avg < 30) {
    recommendations.push('• Apply nitrogen fertilizer (urea or ammonium sulfate)');
  }
  
  if (summary.potassium.avg < 120) {
    recommendations.push('• Apply potash fertilizer for better fruit quality');
  }
  
  if (recommendations.length === 0) {
    recommendations.push('• Maintain current practices - soil health is good');
  }
  
  return recommendations;
};
